### ISSUE TITLE
Yank not detecting CUDA platform on linux

### ISSUE THREAD

**Issue by spadavec** [choderalab/yank#628]
I just built a new linux box with 2 gtx1080s, and it looks like YANK can't pick up the CUDA installation on it. It looks like the issue is that some libOpenMMRPMDCUDA* files couldn't be found (which is weird, because that directory does exist, and I even modified permissions on that dir). Any ideas how to fix this?

```
yanker@hopper:~$ yank --version
0.14.1

yanker@hopper:~$ echo $PATH
/home/spadavec/bin:/home/spadavec/.local/bin:/home/spadavec/miniconda2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda-8.0/bin

yanker@hopper:~$ echo $LD_LIBRARY_PATH
/usr/local/cuda-8.0/lib64/

yanker@hopper:~$ echo $OPENMM_CUDA_COMPILER
/usr/local/cuda-8.0/bin/nvcc

yanker@hopper:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Sun_Sep__4_22:14:01_CDT_2016
Cuda compilation tools, release 8.0, V8.0.44

yanker@hopper:~$ nvidia-smi
Sun Jan 22 14:02:57 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 0000:01:00.0      On |                  N/A |
|  0%   29C    P8     8W / 198W |    464MiB /  8110MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 1080    Off  | 0000:04:00.0     Off |                  N/A |
|  0%   27C    P8     6W / 198W |      1MiB /  8113MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      3287    G   /usr/lib/xorg/Xorg                             212MiB |
|    0      4097    G   compiz                                         204MiB |
+-----------------------------------------------------------------------------+

yanker@hopper:~$ yank platforms
/home/yanker/miniconda2/lib/python2.7/site-packages/numexpr/cpuinfo.py:42: UserWarning: [Errno 2] No such file or directory
  warnings.warn(str(e), UserWarning, stacklevel=stacklevel)
Available OpenMM platforms:
    0 Reference
    1 CPU
    2 OpenCL

yanker@hopper:~$ yank selftest


YANK Selftest
-------------
Yank Version 0.14.1 

Available OpenMM platforms:
    0 Reference
    1 CPU
    2 OpenCL

************************************************

Warning! There were OpenMM Platform Load Errors!
************************************************
Error loading library /home/yanker/miniconda2/lib/plugins/libOpenMMCUDA.so: libcufft.so.7.5: cannot open shared object file: No such file or directory
Error loading library /home/yanker/miniconda2/lib/plugins/libOpenMMRPMDCUDA.so: libOpenMMCUDA.so: cannot open shared object file: No such file or directory
Error loading library /home/yanker/miniconda2/lib/plugins/libOpenMMDrudeCUDA.so: libOpenMMCUDA.so: cannot open shared object file: No such file or directory
Error loading library /home/yanker/miniconda2/lib/plugins/libOpenMMAmoebaCUDA.so: libOpenMMCUDA.so: cannot open shared object file: No such file or directory
************************************************
************************************************


Valid OpenEye install not found
Not required, but please check install if you expected it


Checking GPU Computed Mode (if present)...
Found 2 NVIDIA GPUs in the following modes: [Default, Default]
These should all be in shared/Default mode for YANK to use them
YANK Selftest complete.
Thank you for using YANK!

yanker@hopper:~/miniconda2/lib/plugins$ ls -al
total 16268
drwxrwxr-x 2 yanker yanker    4096 Jan 14 14:41 .
drwxrwxr-x 9 yanker yanker   12288 Jan 14 14:41 ..
-rwxrwxrwx 2 yanker yanker 1426584 May 25  2016 libOpenMMAmoebaCUDA.so
-rwxrwxrwx 2 yanker yanker 1586424 May 25  2016 libOpenMMAmoebaReference.so
-rwxrwxrwx 2 yanker yanker 2307872 May 25  2016 libOpenMMCPU.so
-rwxrwxrwx 2 yanker yanker 4575608 May 25  2016 libOpenMMCUDA.so
-rwxrwxrwx 2 yanker yanker  308712 May 25  2016 libOpenMMDrudeCUDA.so
-rwxrwxrwx 2 yanker yanker  351432 May 25  2016 libOpenMMDrudeOpenCL.so
-rwxrwxrwx 2 yanker yanker  221976 May 25  2016 libOpenMMDrudeReference.so
-rwxrwxrwx 2 yanker yanker 4833776 May 25  2016 libOpenMMOpenCL.so
-rwxrwxrwx 2 yanker yanker  138096 May 25  2016 libOpenMMPME.so
-rwxrwxrwx 2 yanker yanker  296576 May 25  2016 libOpenMMRPMDCUDA.so
-rwxrwxrwx 2 yanker yanker  339632 May 25  2016 libOpenMMRPMDOpenCL.so
-rwxrwxrwx 2 yanker yanker  226880 May 25  2016 libOpenMMRPMDReference.so

```

**Comment by jchodera** [comment]
It looks like you have a version of `openmm` built against CUDA 7.5 installed.  Try this:
```bash
conda install --yes -c omnia/label/dev openmm==7.2.0
```
We're about to release OpenMM 7.1.0 built against CUDA 8, which should solve this issue in a few days.

**Comment by spadavec** [comment]
That was totally it, thanks @jchodera

**Comment by jchodera** [comment]
Great!

**Comment by jeiros** [comment]
Hi, I'm getting exactly the same problem, but with CUDA 7.5.
```bash
$ yank --version
0.15.0
$ echo $PATH
/home/je714/miniconda2/bin:/usr/local/cuda-7.5/bin:/usr/lib64/qt-3.3/bin:/home/je714/perl5/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/openlava-3.0/bin:/home/je714/.local/bin:/home/je714/bin
$ echo $LD_LIBRARY_PATH
/usr/local/cuda-7.5/lib64:/usr/local/intel:
$ echo $OPENMM_CUDA_COMPILER
/usr/local/cuda-7.5/bin/nvcc
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:27:32_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17
$ nvidia-smi
Thu Feb 16 12:11:13 2017
+------------------------------------------------------+
| NVIDIA-SMI 352.63     Driver Version: 352.63         |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  On   | 0000:05:00.0     Off |                  N/A |
| 77%   87C    P2   175W / 250W |    949MiB / 12287MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  On   | 0000:06:00.0     Off |                  N/A |
| 82%   88C    P2   193W / 250W |   6202MiB / 12287MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  On   | 0000:09:00.0     Off |                  N/A |
| 60%   84C    P2   160W / 250W |    381MiB / 12287MiB |     98%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  On   | 0000:0A:00.0     Off |                  N/A |
| 22%   49C    P8    15W / 250W |     23MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      9493    C   /usr/local/amber/bin/pmemd.cuda_SPFP           924MiB |
|    1     27725    C   /usr/local/amber/bin/pmemd.cuda_SPFP          6176MiB |
|    2     17302    C   /usr/local/amber/bin/pmemd.cuda_SPFP           356MiB |
+-----------------------------------------------------------------------------+
$ yank platforms
Available OpenMM platforms:
    0 Reference
    1 CPU
    2 OpenCL

$ yank selftest

YANK Selftest
-------------
Yank Version 0.15.0

Available OpenMM platforms:
    0 Reference
    1 CPU
    2 OpenCL

************************************************

Warning! There were OpenMM Platform Load Errors!
************************************************
Error loading library /home/je714/miniconda2/lib/plugins/libOpenMMCUDA.so: libcufft.so.8.0: cannot open shared object file: No such file or directory
Error loading library /home/je714/miniconda2/lib/plugins/libOpenMMRPMDCUDA.so: libOpenMMCUDA.so: cannot open shared object file: No such file or directory
Error loading library /home/je714/miniconda2/lib/plugins/libOpenMMDrudeCUDA.so: libOpenMMCUDA.so: cannot open shared object file: No such file or directory
Error loading library /home/je714/miniconda2/lib/plugins/libOpenMMAmoebaCUDA.so: libOpenMMCUDA.so: cannot open shared object file: No such file or directory
Error loading library /home/je714/miniconda2/lib/plugins/libOpenMMCudaCompiler.so: libnvrtc.so.8.0: cannot open shared object file: No such file or directory
************************************************
************************************************


Valid OpenEye install not found
Not required, but please check install if you expected it


Checking GPU Computed Mode (if present)...
Found 4 NVIDIA GPUs in the following modes: [Default, Default, Default, Default]
These should all be in shared/Default mode for YANK to use them
YANK Selftest complete.
Thank you for using YANK!
$ ls -al ~/miniconda2/lib/plugins
total 17148
drwxrwxr-x. 2 je714 je714    4096 Feb 16 12:06 .
drwxrwxr-x. 9 je714 je714    8192 Feb 16 12:06 ..
-rwxrwxr-x. 2 je714 je714 1404760 Feb 15 22:38 libOpenMMAmoebaCUDA.so
-rwxrwxr-x. 2 je714 je714 1612320 Feb 15 22:38 libOpenMMAmoebaReference.so
-rwxrwxr-x. 2 je714 je714 2603576 Feb 15 22:38 libOpenMMCPU.so
-rwxrwxr-x. 2 je714 je714  118200 Feb 15 22:38 libOpenMMCudaCompiler.so
-rwxrwxr-x. 2 je714 je714 4827680 Feb 15 22:38 libOpenMMCUDA.so
-rwxrwxr-x. 2 je714 je714  308736 Feb 15 22:38 libOpenMMDrudeCUDA.so
-rwxrwxr-x. 2 je714 je714  351456 Feb 15 22:38 libOpenMMDrudeOpenCL.so
-rwxrwxr-x. 2 je714 je714  222000 Feb 15 22:38 libOpenMMDrudeReference.so
-rwxrwxr-x. 2 je714 je714 5073552 Feb 15 22:38 libOpenMMOpenCL.so
-rwxrwxr-x. 2 je714 je714  138352 Feb 15 22:38 libOpenMMPME.so
-rwxrwxr-x. 2 je714 je714  296600 Feb 15 22:38 libOpenMMRPMDCUDA.so
-rwxrwxr-x. 2 je714 je714  339656 Feb 15 22:38 libOpenMMRPMDOpenCL.so
-rwxrwxr-x. 2 je714 je714  226904 Feb 15 22:38 libOpenMMRPMDReference.so
```

I tried @jchodera recommendation `conda install --yes -c omnia/label/dev openmm==7.2.0`, then
removed and reinstalled `yank`. But the error still comes up. Here's the packages that are installed
at the moment:
```
$ conda list
# packages in environment at /home/je714/miniconda2:
#
alabaster                 0.7.9                    py27_0
alchemy                   1.2.3                    py27_0    omnia
ambermini                 16.16.0                       7    omnia
babel                     2.3.4                    py27_0
cffi                      1.9.1                    py27_0
clusterutils              0.1.2                    py27_0    omnia
conda                     4.3.11                   py27_0
conda-env                 2.6.0                         0
cryptography              1.7.1                    py27_0
curl                      7.49.0                        1
cython                    0.25.2                   py27_0
docopt                    0.6.2                    py27_1    omnia
docutils                  0.13.1                   py27_0
enum34                    1.1.6                    py27_0
fftw3f                    3.3.4                         2    omnia
hdf4                      4.2.12                        0
hdf5                      1.8.17                        1
idna                      2.2                      py27_0
imagesize                 0.7.1                    py27_0
ipaddress                 1.0.18                   py27_0
jinja2                    2.9.4                    py27_0
jpeg                      8d                            2
latexcodec                1.0.1                    py27_0    omnia
libffi                    3.2.1                         1
libgcc                    5.2.0                         0
libgfortran               3.0.0                         1
libnetcdf                 4.4.1                         0
markupsafe                0.23                     py27_2
mdtraj                    1.8.0               np111py27_1    omnia
mkl                       2017.0.1                      0
mpi4py                    2.0.0                    py27_2
mpich2                    1.4.1p1                       0
netcdf4                   1.2.4               np111py27_0
nose                      1.3.7                    py27_1
numexpr                   2.6.2               np111py27_0
numpy                     1.11.3                   py27_0
numpydoc                  0.6.0                    py27_0
openmm                    7.2.0                    py27_0    omnia/label/dev
openmmtools               0.8.3                    py27_1    omnia
openmoltools              0.7.4                    py27_0    omnia
openssl                   1.0.2k                        0
oset                      0.1.3                    py27_1    omnia
pandas                    0.19.2              np111py27_1
parmed                    2.7.3                    py27_0    omnia
pip                       9.0.1                    py27_1
pyasn1                    0.1.9                    py27_0
pybtex                    0.18                     py27_0    omnia
pybtex-docutils           0.2.1                    py27_1    omnia
pycosat                   0.6.1                    py27_1
pycparser                 2.17                     py27_0
pygments                  2.1.3                    py27_0
pymbar                    3.0.0.beta2         np111py27_0    omnia
pyopenssl                 16.2.0                   py27_0
pytables                  3.3.0               np111py27_0
python                    2.7.13                        0
python-dateutil           2.6.0                    py27_0
pytz                      2016.10                  py27_0
pyyaml                    3.12                     py27_0
readline                  6.2                           2
requests                  2.12.4                   py27_0
ruamel_yaml               0.11.14                  py27_1
schema                    0.6.2                    py27_0    omnia
scipy                     0.18.1              np111py27_1
setuptools                27.2.0                   py27_0
six                       1.10.0                   py27_0
snowballstemmer           1.2.1                    py27_0
sphinx                    1.5.1                    py27_0
sphinxcontrib-bibtex      0.3.2                    py27_0    omnia
sqlite                    3.13.0                        0
tk                        8.5.18                        0
wheel                     0.29.0                   py27_0
yaml                      0.1.6                         0
yank                      0.15.0                   py27_0    omnia
zlib                      1.2.8                         3
```
Anything that stands out as wrong?
Thanks for any help.

**Comment by Lnaden** [comment]
@jeiros OpenMM 7.1 and greater are built off CUDA 8.0 and require it as a minimum version. Based on your `nvcc` output, it looks like you are on CUDA 7.5. Are you able to update CUDA to the newest version to use OpenMM 7.1? If not, you may have to downgrade OpenMM to 7.0.1, but that has a number of bugs that will show up in your simulations.

**Comment by jeiros** [comment]
Thanks @Lnaden , downgraded to OpenMM 7.0.1 for the moment and the error went away:
```bash
$ yank selftest


YANK Selftest
-------------
Yank Version 0.15.0

Available OpenMM platforms:
    0 Reference
    1 CPU
    2 CUDA
    3 OpenCL



Valid OpenEye install not found
Not required, but please check install if you expected it


Checking GPU Computed Mode (if present)...
Found 4 NVIDIA GPUs in the following modes: [Default, Default, Default, Default]
These should all be in shared/Default mode for YANK to use them
YANK Selftest complete.
Thank you for using YANK!
```
I'll upgrade to the newer version of CUDA.

**Comment by agreen69** [comment]
Hello,  I am having a similar problem with a more recent version of Yank and with cuda 9.2. I have tried the same version of Yank with cuda 7.5 and  8.0, but I have received the same error messages. 

[a12@or-condo-g04 ~]$ echo $OPENMM_CUDA_COMPILER
/software/dev_tools/swtree/cs400_centos7.2_pe2016-08/cuda/9.2/centos7.2_binary/bin/nvcc
[a12@or-condo-g04 ~]$ echo $LD_LIBRARY_PATH
/software/dev_tools/swtree/cs400_centos7.2_pe2016-08/cuda/9.2/centos7.2_binary/lib64:/software/dev_tools/swtree/cs400_centos7.2_pe2016-08/openmpi/3.0.0/centos7.2_intel18.0.0/lib
[a12@or-condo-g04 ~]$ module load cuda/9.2
[a12@or-condo-g04 ~]$ echo $PATH
/software/dev_tools/swtree/cs400_centos7.2_pe2016-08/cuda/9.2/centos7.2_binary/bin:/home/a12/anaconda3/bin:/home/a12/anaconda3/bin:/home/a12/anaconda3/bin:/home/a12/anaconda3/bin:/home/a12/anaconda3/bin:/home/a12/anaconda3/bin:/software/dev_tools/swtree/cs400_centos7.2_pe2016-08/openmpi/3.0.0/centos7.2_intel18.0.0/bin:/home/a12/miniconda3/bin:/home/a12/anaconda3/bin:/opt/torque/bin:/opt/torque/sbin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/a12/src/g_mmpbsa/bin:/home/a12/src/g_mmpbsa/bin:/home/a12/src/g_mmpbsa/bin:/home/a12/src/g_mmpbsa/bin:/home/a12/src/g_mmpbsa/bin
[a12@or-condo-g04 ~]$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148
[a12@or-condo-g04 ~]$ nvidia-smi
Fri Aug 17 15:00:49 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44                 Driver Version: 396.44                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:05:00.0 Off |                    0 |
| N/A   35C    P0    60W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00000000:06:00.0 Off |                    0 |
| N/A   29C    P0    73W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           Off  | 00000000:83:00.0 Off |                    0 |
| N/A   32C    P0    58W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           Off  | 00000000:84:00.0 Off |                    0 |
| N/A   26C    P0    74W / 149W |      0MiB / 11441MiB |     98%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
[a12@or-condo-g04 ~]$ yank platforms
Available OpenMM platforms:
    0 Reference
    1 CPU
    2 OpenCL

[a12@or-condo-g04 ~]$ yank selftest


YANK Selftest
-------------
Yank Version 0.23.3 

Available OpenMM platforms:
    0 Reference
    1 CPU
    2 OpenCL

************************************************

Warning! There were OpenMM Platform Load Errors!
************************************************
Error loading library /home/a12/anaconda3/lib/plugins/libOpenMMCUDA.so: libcufft.so.9.0: cannot open shared object file: No such file or directory
Error loading library /home/a12/anaconda3/lib/plugins/libOpenMMRPMDCUDA.so: libOpenMMCUDA.so: cannot open shared object file: No such file or directory
Error loading library /home/a12/anaconda3/lib/plugins/libOpenMMDrudeCUDA.so: libOpenMMCUDA.so: cannot open shared object file: No such file or directory
Error loading library /home/a12/anaconda3/lib/plugins/libOpenMMAmoebaCUDA.so: libOpenMMCUDA.so: cannot open shared object file: No such file or directory
Error loading library /home/a12/anaconda3/lib/plugins/libOpenMMCudaCompiler.so: libnvrtc.so.9.0: cannot open shared object file: No such file or directory
************************************************
************************************************


Valid OpenEye install not found
Not required, but please check install if you expected it


Checking GPU Computed Mode (if present)...
Found 4 NVIDIA GPUs in the following modes: [Default, Default, Default, Default]
These should all be in shared/Default mode for YANK to use them
YANK Selftest complete.
Thank you for using YANK!

[a12@or-condo-g04 ~]$ ls -al ~/anaconda3/lib/plugins/
total 3765
drwxr-xr-x  2 a12 users      15 Aug 17 13:56 .
drwxr-xr-x 23 a12 users    1144 Aug 16 12:37 ..
-rwxrwxr-x  2 a12 users  831872 May 10 21:40 libOpenMMAmoebaCUDA.so
-rwxrwxr-x  2 a12 users  547824 May 10 21:40 libOpenMMAmoebaReference.so
-rwxrwxr-x  2 a12 users  612664 May 10 21:40 libOpenMMCPU.so
-rwxrwxr-x  2 a12 users   37136 May 10 21:40 libOpenMMCudaCompiler.so
-rwxrwxr-x  2 a12 users 2474752 May 10 21:40 libOpenMMCUDA.so
-rwxrwxr-x  2 a12 users  107904 May 10 21:40 libOpenMMDrudeCUDA.so
-rwxrwxr-x  2 a12 users  116848 May 10 21:40 libOpenMMDrudeOpenCL.so
-rwxrwxr-x  2 a12 users   72680 May 10 21:40 libOpenMMDrudeReference.so
-rwxrwxr-x  2 a12 users 2688616 May 10 21:40 libOpenMMOpenCL.so
-rwxrwxr-x  2 a12 users   76456 May 10 21:40 libOpenMMPME.so
-rwxrwxr-x  2 a12 users  118480 May 10 21:40 libOpenMMRPMDCUDA.so
-rwxrwxr-x  2 a12 users  131592 May 10 21:40 libOpenMMRPMDOpenCL.so
-rwxrwxr-x  2 a12 users   54816 May 10 21:40 libOpenMMRPMDReference.so

 I have OpenMM 7.2.2 installed through Anaconda. 

Any ideas?

**Comment by jchodera** [comment]
OpenMM 7.2 was built against CUDA 9.0, and the CUDA platform will only appear if you have CUDA 9.0 installed and paths/environment variables appropriately configured.

If you have CUDA 9.2, give the new OpenMM 7.3 dev build a try!
```bash
conda install --yes -c omnia/label/cuda92 openmm
```
You can switch out `cuda92` for other CUDA versions from `cuda75` through `cuda92`, depending on which version of CUDA you have installed.

We're hoping to make use of the anaconda `cudatoolkit` packages to automatically pick up the CUDA Toolkit dependency in future releases once [anaconda builds and posts recent packages](https://github.com/ContinuumIO/anaconda-recipes/issues/140#issuecomment-403977140).
